# docker-compose version
version: "3"
services:
  backend_web:
    container_name: helloworldsonarqube
    image: helloworldsonarqube
    restart: on-failure
    build: ./ 
    ports:
      - "1111:1111"


  sonarqube:
    container_name: sonarqube
    image: sonarqube:8-community
    restart: always
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqubedb
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /opt/sonarCE/data:/opt/sonarqube/data
      - /opt/sonarCE/extentions:/opt/sonarqube/extensions
      - /opt/sonarCE/logs/:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    container_name: postgresql
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqubedb
    volumes:
      - /opt/postgresql/:/var/lib/postgresql
      - /opt/postgresql/data:/var/lib/postgresql/data